version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - OPENWEATHERMAP_API_KEY=your_api_key_here
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
